<?php
/**
 * Created by PhpStorm.
 * User: Администратор
 * Date: 15.12.16
 * Time: 14:20
 */

class Product
{

    public $manufacturer;
    public $model;
    public  $description;
    public  $prise;
    public $comments;

    public  function __construct($mnfc , $mdl, $dscr, $prs,$cmmnt )
    {
    $this-> manufacturer = $mnfc;
        $this-> model = $mdl;
        $this-> description= $dscr;
        $this->prise=$prs;
        $this->comments=$cmmnt;

    }

    public function  outPut()
    {
        echo "manufacturer  ". $this-> manufacturer , "<br/>";
        echo "model  ". $this-> model . "<br/>" ;
        echo "description  ". $this->description  ."<br/>" ;
        echo "prise   ". $this-> prise  ."<br/>" ;
        echo "comments   ". $this-> comments  . "<br/>" ;
    }

    }

class Sale extends Product
{
    public $rest;

    public function __construct($mnfc, $mdl, $dscr, $prs, $cmmnt, $rests)
    {
        parent::__construct($mnfc, $mdl, $dscr, $prs, $cmmnt);
        $this-> rests =  $rests;
    }
    public function  outPut()
    {
        parent::outPut(); // TODO: Change the autogenerated stub
    echo "Slave  to   ". $this->rests ;
    }

}

class Actions extends  Product

{
    public  $For;
    public $To;

    public function __construct($mnfc, $mdl, $dscr, $prs, $cmmnt , $Fr , $T)
    {
        parent::__construct($mnfc, $mdl, $dscr, $prs, $cmmnt);
         $this->For = $Fr;
        $this->To = $T;
    }
 public function  outPut()
 {
     parent::outPut(); // TODO: Change the autogenerated stub

     echo  "From  ". $this-> For . "<br/>";
     echo  "TO   ". $this-> To . "<br/>";
 }

}


$arr1=array("Intell","core-i3","6th Generation Intel Core i3 Processors","100$","No comment");
$arr2=array("Intell","core-i5","6th Generation Intel Core i5 Processors","200$","No comment","20");
$arr3=array("Intell","core-i3","6th Generation Intel Core i7 Processors","300$","No comment","20.12.2016","30.12.2016");

foreach ($arr1 as $key)    /// ??? что нужно сделать ???
{                           //// 3и foreach   для вывода инфы ?
   // echo "$key";

}

$tes= new Product("Intell","core-i3","6th Generation Intel Core i3 Processors","100$","No comment");

 $tes-> outPut ();
echo "<br/>";

$tec =new Sale("Intell","core-i5","6th Generation Intel Core i5 Processors","200$","No comment","20"  );
$tec->outPut();
echo "<br/>";echo "<br/>";

$tek =new Actions("Intell","core-i7","6th Generation Intel Core i7 Processors","300$","No comment","20.12.2016","30.12.2016" );
$tek->outPut();
echo "<br/>";


